### ISSUE TITLE
Shortcode for phones upgrade

### ISSUE THREAD

**Issue by vladiiancu** [siteup/wp-device-detect#1]
I would like to enhance the phone shortcode a bit. 
Specifically let's say I have 2 pieces of content. (A and B). I want A to show up on mobile and B on everything else. 
Right now I would write something like this: 
`[phone] My A content [/phone]
[notphone] My B content [/notphone]
`
And this would work.
But perhaps, for certain cases something like this would be more useful:

`
[phone alternativecontent="My B content"] My A content [/phone]
`

Of course with a better name for "alternativecontent" :)

**Comment by peterbuga** [comment]
I don't think this would be a good idea, for now i see problems on users setting the **B-content** as an image or some html code that might contain comas.

**Comment by vladiiancu** [comment]
All right. Then we should add to documentation for users a good example and be done with it :)
